// Build information, automatically generated by `ng-info`
const build = {
    version: "0.1.3",
    timestamp: "Wed Nov 16 2022 14:59:14 GMT+0100 (heure normale d’Europe centrale)",
    message: null,
    git: {
        user: "Théophane VRAUX",
        branch: "main",
        hash: "c862f6",
        fullHash: "c862f6624898631c7431bf735da19c7232dfaff2"
    }
};

export default build;