// Build information, automatically generated by `ng-info`
const build = {
    version: "0.1.2",
    timestamp: "Mon Nov 07 2022 22:17:29 GMT+0100 (heure normale d’Europe centrale)",
    message: null,
    git: {
        user: "Théophane VRAUX",
        branch: "main",
        hash: "28e758",
        fullHash: "28e7589eed41966aec875efc0db8d4882d67c5e5"
    }
};

export default build;