// Build information, automatically generated by `ng-info`
const build = {
    version: "0.1.1",
    timestamp: "Fri Oct 28 2022 17:06:20 GMT+0200 (heure d’été d’Europe centrale)",
    message: null,
    git: {
        user: "Théophane VRAUX",
        branch: "main",
        hash: "6f000e",
        fullHash: "6f000e3c3c8d061d46d1a3552af873a1efa75c91"
    }
};

export default build;